<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>
		<RootNamespace>AddOn.Episerver.Settings</RootNamespace>
		<AssemblyName>AddOn.Episerver.Settings</AssemblyName>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<LangVersion>10</LangVersion>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>true</IsPackable>
		<DebugType>embedded</DebugType>
		<Authors>Linus Ekström, Jeroen Stemerdink, Erik Kärrsgård</Authors>
		<PackageTags>EpiServer Settings AddOn.Episerver.Settings</PackageTags>
		<PackageProjectUrl>https://github.com/LinusEkstrom/AddOn.Episerver.Settings</PackageProjectUrl>
		<Copyright>Copyright © 2022 Linus Ekström, Jeroen Stemerdink, Erik Kärrsgård</Copyright>
		<Description>A typed settings system for Optimizely built on standardized ContentData.</Description>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsNotAsErrors>true</WarningsNotAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="Resources\*.xml" />
	</ItemGroup>
	<ItemGroup>
		<None Include="readme.txt" pack="true" PackagePath="." />
		<None Include="web.config.install.xdt" pack="true" PackagePath="Content" />
		<None Include="web.config.uninstall.xdt" pack="true" PackagePath="Content" />
		<None Include="web.config" pack="true" PackageCopyToOutput="true" PackageFlatten="false" PackagePath="Content\modules\_protected\AddOn.Episerver.Settings" />
		<None Include="AddOn.Episerver.Settings.zip" pack="true" PackageCopyToOutput="true" PackageFlatten="false" PackagePath="Content\modules\_protected\AddOn.Episerver.Settings" />
		<None Include="AddOn.Episerver.Settings.zip" pack="true" PackageCopyToOutput="true" PackageFlatten="false" PackagePath="contentFiles\any\any\modules\_protected\AddOn.Episerver.Settings" />
		<None Include="..\..\templates\SettingsTemplates.DotSettings" pack="true" PackagePath="Tools" />
		<None Include="AddOn.Episerver.Settings.targets" pack="true" PackagePath="Build\net10.0" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="EPiServer.CMS.AspNetCore.Templating" Version="[13.0.2, 14)" />
		<PackageReference Include="EPiServer.CMS.UI.Core" Version="[13.0.2, 14)" />
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
