name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  BUILD_CONFIGURATION: 'Release'
  DOTNET_VERSION: '8.0.x'
  CWD: './src'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        include-prerelease: true
    - name: Build
      working-directory: ${{ env.CWD }}
      run: |
        dotnet nuget add source https://nuget.episerver.com/feed/packages.svc --name Optimizely
        dotnet restore
        dotnet build --no-restore --configuration '${{ env.BUILD_CONFIGURATION }}'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: './src/AddOn.Episerver.Settings/bin/Release/*.nupkg'
